### ISSUE TITLE
"sub-outcode" method

### ISSUE THREAD

**Issue by billinghamj** [ideal-postcodes/postcode#3]
I've just started integrating a new data set into one of our systems, and _sigh_ the postcode mappings use a funky version of standard outcodes.

For most cases, the full outcode is correct. e.g.:
- AB1 1AB -> AB1
- AA11 1AA -> AA11

But for the few London outcodes which end with letters, the letter is excluded. e.g.:
- EC1V 1AA -> EC1
- AA1A 1AA -> AA1

This seems like something useful to support in postcode.js. The only issue is I'm not sure what this would be called. It's not documented anywhere from what I can tell.

Any opinions/ideas naming-wise? I'll submit a PR once a name is figured out.

Thanks!

**Comment by cblanc** [comment]
That's an interesting use case. 

I'm struggling to come up with an a simple name that encapsulates what it does. `subOutcode` is better than all the ones I can think of

I suppose as long as the method is well documented in the readme it won't be the end of the world if the perfect name can't be found

**Comment by stephenkeable** [comment]
Pretty sure it's known as a "sub district" 

Stephen Keable
www.stephenkeable.co.uk

**Comment by billinghamj** [comment]
Wikipedia article seems to agree:

https://en.m.wikipedia.org/wiki/London_postal_district#Numbered_divisions

I'll define two new methods:
- `district` - alias of `outcode`
- `subDistrict` - district without number

**Comment by stephenkeable** [comment]
I work at Allies Computing where they've been working with postcodes for over 20 years. You tend to pick up the terminology without even trying :)

**Comment by cblanc** [comment]
Perfect. Thanks for the tip Stephen

**Comment by cblanc** [comment]
Perfect. Thanks for the tip @stephenkeable 

If you're ever looking for work around London, please allow me to buy you a coffee :D 

Also, I do apologise if I'm stepping out of line :-)

**Comment by billinghamj** [comment]
Oh actually, "sub district" would mean _with_ the number. So I think it should probably work like this:

For outcodes ending with a number:
- `district` - returns `outcode` without the number
- `subDistrict` - returns `outcode` as-is

For outcodes not ending with a number:
- `district` - returns `outcode` as-is
- `subDistrict` - returns `null`

This would then allow you to do `!postcode.subDistrict()` to determine if it is a London high density district or not.

Just needs to be carefully documented.

`outcode` would continue to work exactly as-is.

**Comment by stephenkeable** [comment]
The outcode without the number is a Postcode Area not a district.

For NR14 7PZ

NR14 = Outcode
7PZ = Incode

NR = Postcode area
NR14 = Postcode district
NR14 7 = Postcode sector
PZ = Postcode unit

If NR1 ever got too crowded they might create NR1W and NR1E as West and East “Sub districts”. 

Not sure what Royal Mail will do should two digit postcode districts need to be sub divided.

**Comment by billinghamj** [comment]
Yup. That's how it's implemented in the library. Examples are in the readme :)
