### ISSUE TITLE
Can I use this package without a module? **help not issue**

### ISSUE THREAD

**Issue by flatcapco** [ideal-postcodes/postcode#383]
Thanks for the great package it looks super powerful and well documented.

I'm a little stuck with how to use it though, I have a simple wordpress project that doesn't have any module loading.

So I popped in laravel mix (webpack) and I have it console.logging a const of a postcode with the expected result.. however I cant work out how to make a function so I can dynamically check various postcodes. 

Is this package available outside of modules / imports or is there a handy tip you can pass on to make functions public?

Thanks

**Comment by cblanc** [comment]
I have 2 guesses for how to do this on webpack - although I'm not very familiar with this bundler

1. I think [Shimming](https://webpack.js.org/guides/shimming/) might be the official solution for exporting bundled dependencies into global scope

2. Export the function you're interested to `window`

```javascript
import { parse } from "postcode";

window.postcodeParse = parse;
```

**Comment by flatcapco** [comment]
You hero. As if it was that simple! I was trying to get it with window.parse, exporting default functions and all sorts! 
I didn't even need to do any "shimming" just passing it to window made it available!

Thanks so much :)
