### ISSUE TITLE
new Postcode('junk') != null

### ISSUE THREAD

**Issue by alanshaw** [ideal-postcodes/postcode#6]
From the code it looks like creating a `new Postcode` with an invalid postcode should just return null.
https://github.com/ideal-postcodes/postcode.js/blob/master/index.js#L39-L41

...but this isn't what happens in JavaScript:

``` js
$ node
> function Thing () { return null }
undefined
> new Thing
Thing {}
> 
```

I suggest these lines are removed as a) they don't do anything and b) it can cause developers (me) to make incorrect assumptions about the code!

**Comment by cblanc** [comment]
You're right, it shouldn't be there. Even if it did return `null` instead of an object, that would create a number of problems. Thanks for taking the time
