### ISSUE TITLE
Valid postcode E15 2EN is not accepted.

### ISSUE THREAD

**Issue by ghost** [ideal-postcodes/postcode#9]
Newly added postcode "E15 2EN" is valid but it is not accepted by the library.
<img width="293" alt="valid-postcode" src="https://user-images.githubusercontent.com/10720760/28722339-0726450a-73d1-11e7-97e5-e2459c09e53e.png">

**Comment by cblanc** [comment]
Hi there

Could you show the code to replicate this? I was not able to on my end

```
> const Postcode = require("postcode");
undefined
> const postcode = new Postcode("E15 2EN");
undefined
> postcode.valid();
true
```

**Comment by cblanc** [comment]
Also, according to ONSPD, E15 2EN was dropped in February 2015
